name: Test

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/CI.yml'
      - '.github/workflows/tag.yml'
      - 'discrete_dists/**'
      - 'rust/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/CI.yml'
      - '.github/workflows/tag.yml'
      - 'discrete_dists/**'
      - 'rust/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'requirements.txt'

concurrency:
  group: test-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o requirements.txt
          uv pip sync requirements.txt
          source .venv/bin/activate
          maturin develop --release

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release

      - run: pytest tests/
